openapi: 3.0.0
info:
  title: Reviews Endpoints Documentation
  description: Doccuments all reviews endpoints in the routes/Reviews.ts file
  version: 1.0.0
servers:
  - url: http://144.22.196.74:52368
    description: Branch developer's server
paths:
  /review/{idUser}:
    post:
      summary: Creates a new user review of a movie
      parameters:
        - in: path
          name: idUser
          description: User's ID (must be a Types.ObjectId)
          required: true
          schema:
            type: objectId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                review:
                  type: string
                rating:
                  type: number
                movieId:
                  type: objectID
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid user/movie ID format
        '403': 
          description: User not authorized
        '404':
          description: User/movie not found
        '500':
          description: Internal server error
